CONFIG_GPIO=y

CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_UART_LINE_CTRL=y
CONFIG_LOG=y

CONFIG_BUILD_OUTPUT_UF2=n

CONFIG_SERIAL=y
CONFIG_GPIO=y
CONFIG_BOOTLOADER_MCUBOOT=n
CONFIG_USE_DT_CODE_PARTITION=n
CONFIG_FLASH_LOAD_OFFSET=0

CONFIG_LED_STRIP=y

CONFIG_ADC=y

# Display support - SPI only
CONFIG_DISPLAY=y
CONFIG_SPI=y

# ST7735 display driver  
CONFIG_ST7789V=y

# SX1262 support
CONFIG_LORA=y
CONFIG_LORA_SX126X=y

# GNSS support
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_RING_BUFFER=y
CONFIG_GNSS=y
CONFIG_GNSS_SATELLITES=y
CONFIG_STATIC_INIT_GNU=y