manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: zephyr-fork
      url-base: https://github.com/fgr-17

  defaults:
    remote: zephyrproject

  projects:
    - name: zephyr
      path: zephyr
      remote: zephyr-fork
      # revision: v4.3.0
      revision: heltec_t114_v2
      import: true
      west-commands: scripts/west-commands.yml 

  self:
    path: .